version: "3"
services:
  master:
    image: postgres:12.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres" # Specify the database user name
      POSTGRES_PASSWORD: "P0stgres" # Specify the user password
      POSTGRES_DB: "dvdrental" # Specify the database name
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C" # Specify encoding and locale
    volumes:
      - ./master:/docker-entrypoint-initdb.d
  postgis:
    image: postgis/postgis:12-3.2-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: "postgres" # Specify the database user name
      POSTGRES_PASSWORD: "P0stgres" # Specify the user password
      POSTGRES_DB: "dvdrental" # Specify the database name
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C" # Specify encoding and locale
    volumes:
      - ./master:/docker-entrypoint-initdb.d

